seed: 42
batch_size: 4096
num_workers: 2
epoches: 100
learning_rate: 0.02
lambda_sparce: 0.0001  # coefficient before sparce loss function
test_size: 0.2  # Proportion of data in valid_dataset
experiment_name: 'Tabnet_Homework'
run_name: 'Default!'

# Config Modules
defaults:
  - tabnet: tabnet  # Config for classical Tabnet architecture
  - classifier_head: head  # config for classification head
  - optimizer: Adam # Choose optimizer config. Available Adam, AdamW, RMSprop, SGD
  - scheduler: ReduceLROnPlateau  # Scheduler for each optimizer